=== Hanif-Tiznobake/CareerKit.xml/dbo_skill.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="dbo_skill" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="dbo_skill">
<xsd:annotation>
<xsd:appinfo>
<od:tableProperty name="GUID" type="9" value="q+9moI8qHkiVVT2e9zBCvQ==
"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="0"/>
<od:tableProperty name="NameMap" type="11" value="CswOVQAAAACr72agjyoeSJVVPZ73MEK9AAAAAMQaBuQBR+VAAAAAAAAAAABkAGIA
bwBfAHMAawBpAGwAbAAAAAAAAADKvwQJUpVHS5Rnh4C8q6IGBwAAAKvvZqCPKh5I
lVU9nvcwQr1zAGsAaQBsAGwAXwBpAGQAAAAAAAAA/xVIr9SnQEy3AiHaRsMxiQcA
AACr72agjyoeSJVVPZ73MEK9cwBrAGkAbABsAAAAAAAAAK+JEZv8nyZPs1aBR1qa
AeIHAAAAq+9moI8qHkiVVT2e9zBCvWQAZQB0AGEAaQBsAF8AaQBkAAAAAAAAAJKe
FRM/srNJllskqoTdieYHAAAAq+9moI8qHkiVVT2e9zBCvWMAYQB0AGUAZwBvAHIA
eQBfAGkAZAAAAAAAAADgOSa1JA/PTqfZQp8hnt3HBwAAAKvvZqCPKh5IlVU9nvcw
Qr10AGUAbQBwAF8AaQBkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAAAABQAAAAAA
AAAAAAAAAAAAAAAA
"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="DisplayViewsOnSharePointSite" type="2" value="1"/>
<od:tableProperty name="TotalsRow" type="1" value="0"/>
<od:tableProperty name="FilterOnLoad" type="1" value="0"/>
<od:tableProperty name="OrderByOnLoad" type="1" value="1"/>
<od:tableProperty name="HideNewField" type="1" value="0"/>
<od:tableProperty name="BackTint" type="6" value="100"/>
<od:tableProperty name="BackShade" type="6" value="100"/>
<od:tableProperty name="ThemeFontIndex" type="4" value="-1"/>
<od:tableProperty name="AlternateBackThemeColorIndex" type="4" value="-1"/>
<od:tableProperty name="AlternateBackTint" type="6" value="100"/>
<od:tableProperty name="AlternateBackShade" type="6" value="100"/>
<od:tableProperty name="ReadOnlyWhenDisconnected" type="1" value="0"/>
<od:tableProperty name="DatasheetGridlinesThemeColorIndex" type="4" value="-1"/>
<od:tableProperty name="DatasheetForeThemeColorIndex" type="4" value="-1"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="skill_id" minOccurs="1" od:jetType="longinteger" od:sqlSType="int" od:nonNullable="yes" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="Required" type="1" value="1"/>
<od:fieldProperty name="GUID" type="9" value="yr8ECVKVR0uUZ4eAvKuiBg==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="skill" minOccurs="1" od:jetType="text" od:sqlSType="nvarchar" od:nonNullable="yes">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="Required" type="1" value="1"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="GUID" type="9" value="/xVIr9SnQEy3AiHaRsMxiQ==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="detail_id" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="r4kRm/yfJk+zVoFHWpoB4g==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="category_id" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="kp4VEz+ys0mWWySqhN2J5g==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="temp_id" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="4DkmtSQPz06n2UKfIZ7dxw==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== Hanif-Tiznobake/CareerKit.xml/dbo_skill.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="dbo_skill.xsd" generated="2019-04-21T01:26:21">
<dbo_skill>
<skill_id>7</skill_id>
<skill>Data Analysis</skill>
<detail_id>4</detail_id>
<category_id>15</category_id>
</dbo_skill>
<dbo_skill>
<skill_id>11</skill_id>
<skill>Circuit Implementation</skill>
<category_id>15</category_id>
</dbo_skill>
<dbo_skill>
<skill_id>12</skill_id>
<skill>Data Exploration</skill>
<category_id>15</category_id>
</dbo_skill>
<dbo_skill>
<skill_id>1885</skill_id>
<skill>Data Visualization</skill>
<category_id>15</category_id>
</dbo_skill>
<dbo_skill>
<skill_id>1886</skill_id>
<skill>Dimensionality Reduction</skill>
<category_id>15</category_id>
</dbo_skill>
<dbo_skill>
<skill_id>1887</skill_id>
<skill>Classification</skill>
<category_id>15</category_id>
</dbo_skill>
<dbo_skill>
<skill_id>1888</skill_id>
<skill>Clustering</skill>
<category_id>15</category_id>
</dbo_skill>
<dbo_skill>
<skill_id>1889</skill_id>
<skill>Regression</skill>
<category_id>15</category_id>
</dbo_skill>
<dbo_skill>
<skill_id>1890</skill_id>
<skill>Deep Learning</skill>
<category_id>15</category_id>
</dbo_skill>
<dbo_skill>
<skill_id>1891</skill_id>
<skill>Time Domain Analysis</skill>
<category_id>15</category_id>
</dbo_skill>
<dbo_skill>
<skill_id>1892</skill_id>
<skill>Filter Design</skill>
<category_id>15</category_id>
</dbo_skill>
<dbo_skill>
<skill_id>1893</skill_id>
<skill>Signal Modeling</skill>
<category_id>15</category_id>
</dbo_skill>
<dbo_skill>
<skill_id>1894</skill_id>
<skill>Source Separation</skill>
<category_id>15</category_id>
</dbo_skill>
<dbo_skill>
<skill_id>1895</skill_id>
<skill>Geometric Transforms</skill>
<category_id>15</category_id>
</dbo_skill>
<dbo_skill>
<skill_id>1896</skill_id>
<skill>Segmentation</skill>
<category_id>15</category_id>
</dbo_skill>
<dbo_skill>
<skill_id>1897</skill_id>
<skill>Feature Extraction</skill>
<detail_id>5</detail_id>
<category_id>15</category_id>
</dbo_skill>
<dbo_skill>
<skill_id>1898</skill_id>
<skill>Freq. Domain Analysis</skill>
<category_id>15</category_id>
</dbo_skill>
<dbo_skill>
<skill_id>1899</skill_id>
<skill>Object Recognition</skill>
<category_id>15</category_id>
</dbo_skill>
<dbo_skill>
<skill_id>1900</skill_id>
<skill>Functional Programming</skill>
<category_id>15</category_id>
</dbo_skill>
<dbo_skill>
<skill_id>1901</skill_id>
<skill>Procedural Programming</skill>
<category_id>15</category_id>
</dbo_skill>
<dbo_skill>
<skill_id>1902</skill_id>
<skill>Object-Oriented Programming</skill>
<category_id>15</category_id>
</dbo_skill>
<dbo_skill>
<skill_id>1903</skill_id>
<skill>Unit Test</skill>
<category_id>15</category_id>
</dbo_skill>
<dbo_skill>
<skill_id>1904</skill_id>
<skill>UI Design</skill>
<category_id>15</category_id>
</dbo_skill>
<dbo_skill>
<skill_id>1905</skill_id>
<skill>Analog Circuit Design</skill>
<category_id>15</category_id>
</dbo_skill>
<dbo_skill>
<skill_id>1906</skill_id>
<skill>Logic Circuit Design</skill>
<category_id>15</category_id>
</dbo_skill>
<dbo_skill>
<skill_id>1907</skill_id>
<skill>Communication Circuit Design</skill>
<category_id>15</category_id>
</dbo_skill>
<dbo_skill>
<skill_id>1908</skill_id>
<skill>Waveguide Design</skill>
<category_id>15</category_id>
</dbo_skill>
<dbo_skill>
<skill_id>1909</skill_id>
<skill>Microstrip Design</skill>
<category_id>15</category_id>
</dbo_skill>
<dbo_skill>
<skill_id>1910</skill_id>
<skill>Feedback Control Design</skill>
<category_id>15</category_id>
</dbo_skill>
<dbo_skill>
<skill_id>1911</skill_id>
<skill>Freq. Response Analysis</skill>
<category_id>15</category_id>
</dbo_skill>
<dbo_skill>
<skill_id>1912</skill_id>
<skill>Robustness Analysis</skill>
<category_id>15</category_id>
</dbo_skill>
<dbo_skill>
<skill_id>1913</skill_id>
<skill>Noise Modeling</skill>
<category_id>15</category_id>
</dbo_skill>
<dbo_skill>
<skill_id>1914</skill_id>
<skill>Feature Selection</skill>
<category_id>15</category_id>
</dbo_skill>
<dbo_skill>
<skill_id>1915</skill_id>
<skill>Object Tracking</skill>
<category_id>15</category_id>
</dbo_skill>
<dbo_skill>
<skill_id>1916</skill_id>
<skill>Analog Circuit Implementation</skill>
<category_id>15</category_id>
</dbo_skill>
<dbo_skill>
<skill_id>1917</skill_id>
<skill>Thresholding</skill>
<category_id>15</category_id>
</dbo_skill>
<dbo_skill>
<skill_id>1918</skill_id>
<skill>Point Cloud Registration</skill>
<category_id>15</category_id>
</dbo_skill>
<dbo_skill>
<skill_id>1923</skill_id>
<skill>Depth Perception</skill>
<category_id>15</category_id>
</dbo_skill>
<dbo_skill>
<skill_id>1936</skill_id>
<skill>Spatial Filters</skill>
<category_id>15</category_id>
</dbo_skill>
<dbo_skill>
<skill_id>1938</skill_id>
<skill>Image Transforms</skill>
<category_id>15</category_id>
</dbo_skill>
<dbo_skill>
<skill_id>1940</skill_id>
<skill>Database Design</skill>
<category_id>15</category_id>
</dbo_skill>
<dbo_skill>
<skill_id>1941</skill_id>
<skill>Data Manipulation</skill>
<category_id>15</category_id>
</dbo_skill>
<dbo_skill>
<skill_id>1942</skill_id>
<skill>Data Conversion</skill>
<category_id>15</category_id>
</dbo_skill>
<dbo_skill>
<skill_id>1943</skill_id>
<skill>Data Migration</skill>
<category_id>15</category_id>
</dbo_skill>
<dbo_skill>
<skill_id>1944</skill_id>
<skill>End-user Programming</skill>
<category_id>15</category_id>
</dbo_skill>
<dbo_skill>
<skill_id>1946</skill_id>
<skill>Version Control</skill>
<category_id>15</category_id>
</dbo_skill>
<dbo_skill>
<skill_id>1948</skill_id>
<skill>Signal Transform</skill>
<category_id>15</category_id>
</dbo_skill>
<dbo_skill>
<skill_id>1950</skill_id>
<skill>Model Evaluation</skill>
<category_id>15</category_id>
</dbo_skill>
<dbo_skill>
<skill_id>1951</skill_id>
<skill>System Visualization</skill>
<category_id>15</category_id>
</dbo_skill>
<dbo_skill>
<skill_id>1952</skill_id>
<skill>Signal Visualization</skill>
<category_id>15</category_id>
</dbo_skill>
<dbo_skill>
<skill_id>1953</skill_id>
<skill>Business Intelligence</skill>
<category_id>15</category_id>
</dbo_skill>
<dbo_skill>
<skill_id>1954</skill_id>
<skill>Web Development</skill>
<category_id>15</category_id>
</dbo_skill>
<dbo_skill>
<skill_id>1955</skill_id>
<skill>Signal Processing</skill>
<category_id>15</category_id>
</dbo_skill>
<dbo_skill>
<skill_id>1956</skill_id>
<skill>Image Processing</skill>
<category_id>15</category_id>
</dbo_skill>
<dbo_skill>
<skill_id>1957</skill_id>
<skill>Pattern Recognition</skill>
<category_id>15</category_id>
</dbo_skill>
<dbo_skill>
<skill_id>1958</skill_id>
<skill>Data Science</skill>
<category_id>15</category_id>
</dbo_skill>
<dbo_skill>
<skill_id>1959</skill_id>
<skill>Computer Vision</skill>
<category_id>15</category_id>
</dbo_skill>
<dbo_skill>
<skill_id>1960</skill_id>
<skill>Machine Vision</skill>
<category_id>15</category_id>
</dbo_skill>
<dbo_skill>
<skill_id>1961</skill_id>
<skill>Machine Learning</skill>
<category_id>15</category_id>
</dbo_skill>
<dbo_skill>
<skill_id>1962</skill_id>
<skill>Software Engineering</skill>
<category_id>15</category_id>
</dbo_skill>
<dbo_skill>
<skill_id>1963</skill_id>
<skill>Control System Design</skill>
<category_id>15</category_id>
</dbo_skill>
<dbo_skill>
<skill_id>1964</skill_id>
<skill>Antenna Design</skill>
<category_id>15</category_id>
</dbo_skill>
<dbo_skill>
<skill_id>1965</skill_id>
<skill>Circuit Design</skill>
<category_id>15</category_id>
</dbo_skill>
<dbo_skill>
<skill_id>1966</skill_id>
<skill>Microwave Design</skill>
<category_id>15</category_id>
</dbo_skill>
<dbo_skill>
<skill_id>1967</skill_id>
<skill>Electronics</skill>
<category_id>15</category_id>
</dbo_skill>
<dbo_skill>
<skill_id>1969</skill_id>
<skill>Optimization</skill>
<category_id>15</category_id>
</dbo_skill>
<dbo_skill>
<skill_id>1970</skill_id>
<skill>SIFT</skill>
<category_id>13</category_id>
</dbo_skill>
<dbo_skill>
<skill_id>1971</skill_id>
<skill>SURF</skill>
<category_id>13</category_id>
</dbo_skill>
<dbo_skill>
<skill_id>1972</skill_id>
<skill>HOG</skill>
<category_id>13</category_id>
</dbo_skill>
<dbo_skill>
<skill_id>1973</skill_id>
<skill>LoG</skill>
<category_id>13</category_id>
</dbo_skill>
<dbo_skill>
<skill_id>1974</skill_id>
<skill>Hough Transform</skill>
<category_id>13</category_id>
</dbo_skill>
<dbo_skill>
<skill_id>1975</skill_id>
<skill>Connected Component Analysis</skill>
<category_id>13</category_id>
</dbo_skill>
<dbo_skill>
<skill_id>1976</skill_id>
<skill>Watershed</skill>
<category_id>13</category_id>
</dbo_skill>
<dbo_skill>
<skill_id>1977</skill_id>
<skill>SVM</skill>
<category_id>13</category_id>
</dbo_skill>
<dbo_skill>
<skill_id>1978</skill_id>
<skill>Artificial Neural Network (ANN)</skill>
<category_id>13</category_id>
</dbo_skill>
<dbo_skill>
<skill_id>1979</skill_id>
<skill>Na√Øve Bayes</skill>
<category_id>13</category_id>
</dbo_skill>
<dbo_skill>
<skill_id>1980</skill_id>
<skill>Decision Tree</skill>
<category_id>13</category_id>
</dbo_skill>
<dbo_skill>
<skill_id>1981</skill_id>
<skill>Random Forest</skill>
<category_id>13</category_id>
</dbo_skill>
<dbo_skill>
<skill_id>1982</skill_id>
<skill>k-Means</skill>
<category_id>13</category_id>
</dbo_skill>
<dbo_skill>
<skill_id>1983</skill_id>
<skill>Fuzzy C-means</skill>
<category_id>13</category_id>
</dbo_skill>
<dbo_skill>
<skill_id>1984</skill_id>
<skill>PCA</skill>
<category_id>13</category_id>
</dbo_skill>
<dbo_skill>
<skill_id>1985</skill_id>
<skill>ICA</skill>
<category_id>13</category_id>
</dbo_skill>
<dbo_skill>
<skill_id>1986</skill_id>
<skill>Python</skill>
<category_id>12</category_id>
</dbo_skill>
<dbo_skill>
<skill_id>1987</skill_id>
<skill>MATLAB</skill>
<category_id>12</category_id>
</dbo_skill>
<dbo_skill>
<skill_id>1988</skill_id>
<skill>C/C++</skill>
<category_id>12</category_id>
</dbo_skill>
<dbo_skill>
<skill_id>1989</skill_id>
<skill>JavaScript</skill>
<category_id>12</category_id>
</dbo_skill>
<dbo_skill>
<skill_id>1990</skill_id>
